name: Create new release

on:
  push:
#    branches:
#      - dev
    # When a version tag is pushed.
    tags:
#      - '[0-9]+(\.[0-9]+){2}'
      - '3\..*'
#      - '[0-9]+(\.[0-9]+){2}(-[a-zA-Z]+)?'

jobs:
  build:
    name: Build a downloader
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    - name: Download chrome driver
      run: |
        # Get latest version number.
        VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        
        # Download chromedriver for your OS.
        if [[ $OSTYPE == "linux-gnu" ]]; then
          URL="https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_linux64.zip"
        elif [[ $OSTYPE == "darwin"* ]]; then
          URL="https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_mac64.zip"
        elif [[ $OSTYPE == "win32" ]]; then
          URL="https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_win32.zip"
        else
          echo "Error: Unsupported operating system $OSTYPE"
          exit 1
        fi
        
        # Download and extract chromedriver.
        curl -O $URL
        unzip chromedriver*.zip
        rm chromedriver*.zip

    - name: Build with Maven
      run: mvn clean package -B --file pom.xml

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: echo 'github.ref = ${{ github.ref }}'

      - name: Attach artifacts
        uses: ncipollo/release-action@v1
        with:
#          name: 'v${{ github.ref }}'
          name: ${{ github.ref }}
          draft: true
          makeLatest: true
          skipIfReleaseExists: true
          body: [See changelog](https://github.com/ImSejin/lezhin-comics-downloader/blob/dev/CHANGELOG.md#v305)
          artifacts: 'target/lezhin-comics-downloader.*.*.*.jar'
          artifactContentType: 'application/java-archive'

#      - name: Create draft release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: v${{ github.ref }}
#          draft: true
#          body: [See changelog](https://github.com/ImSejin/lezhin-comics-downloader/blob/dev/CHANGELOG.md#v305)

#      - name: Upload asset
#        uses: actions/upload-artifact@v2.2.4
#        with:
#          name: my-file
#          path: /path/to/my-file

#      - name: Attach asset to release
#        id: attach_asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: '${{ github.workspace }}/target/lezhin-comics-downloader.*.*.*.jar'
#          asset_name: 'lezhin-comics-downloader.jar'
#          asset_content_type: 'application/java-archive'
