name: Create new release

on:
  push:
    branches:
      - dev
    # When a version tag is pushed.
#    tags:
#      - '[0-9]+(\.[0-9]+){2}'

jobs:
  build:
    name: Build a downloader
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    - name: Build with Maven
      run: mvn clean package -B --file pom.xml

  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    needs: build
    permissions: write

    steps:
      - uses: actions/checkout@v3
      - name: Attach artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          draft: true
          makeLatest: true
          skipIfReleaseExists: true
          artifacts: './target/lezhin-comics-downloader.*.*.*.jar'
          artifactContentType: 'application/java-archive'
